# App
spring.application.name=food-delivery
server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/fooddelivery

# JWT
jwt.secret=foodDeliverySecretKey12345foodDeliverySecretKey12345
jwt.expiration=86400000

# Redis ✅ FIXED
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yadavamanindra123@gmail.com
spring.mail.password=crcnjgaejwjapbov
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true