# App
spring.application.name=food-delivery
server.port=8080

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Redis DISABLED
spring.cache.type=none

# Email - Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${GMAIL_USER}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Razorpay
razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
