# App
spring.application.name=food-delivery
server.port=${PORT:8080}

# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# JWT
jwt.secret=foodDeliverySecretKey12345foodDeliverySecretKey12345
jwt.expiration=86400000

# Redis - Disabled
spring.cache.type=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yadavamanindra123@gmail.com
spring.mail.password=crcnjgaejwjapbov
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true